[package]
name = "aws_sts"
version = "0.1.0"
authors = ["Yong Wen Chua <lawliet89@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.19"
log = "0.4"
pretty_env_logger = "0.3.0"
